### ISSUE TITLE
Does it support the Linux platform? 

### ISSUE THREAD

**Issue by c61292558** [brmmm3/RustTaskBarProgress#1]
Does it support the Linux platform?

**Comment by brmmm3** [comment]
Currently not.
I've found this repo which has cross platform support: https://github.com/Skycoder42/QTaskbarControl
When I have some time I can translate this implementation into Rust. But currently I'm too busy.

**Comment by c61292558** [comment]
OK,Thanks for your help. But I'm more looking for a repository that's in the rust language.
